{{- define "ingress.labels" -}}
app.kubernetes.io/project: {{ $.Values.desc.project }}
app.kubernetes.io/component: ingress
app.kubernetes.io/name: {{ $.Release.Name }}
app.kubernetes.io/brand: {{ $.Values.desc.brand }}
app.kubernetes.io/part-of: frontera
app.kubernetes.io/env: {{ $.Values.desc.env }}
{{- end }}

{{- define "frontera.HostnameList" -}}
  {{- $hostList := list -}}
    {{- range .Values.frontera.ingressHostNames -}}
      {{- $hostList = printf "%s" . | append $hostList -}}
    {{- end -}}
  {{ join "," $hostList }}
{{- end -}}
