{{- if .Values.frontera.basicAuth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "basic-auth-%s" .Release.Name }}
  labels: {{ include "common_labels" . | nindent 6 }}
type: nginx.org/htpasswd
stringData:
  htpasswd:
  {{- range .Values.frontera.basicAuth.authData }}
    {{ . }}
  {{- end }}

{{- end }}
