name: Publish Helm Chart

on:
  push:
    tags:
      - "v*"

jobs:
  publish-helm:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: latest

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin

      - name: Package Helm Chart
        run: |
          helm package charts

      - name: Push Helm Chart to GHCR
        run: |
          helm push frontera-domains-records-*.tgz oci://ghcr.io/${{ github.repository_owner }}
